config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

  resources :posts, only: [:show, :new, :create]
  delete "posts/:id", to: "posts#destroy", as: :destroy_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to root_url
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1> Posts </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th width="20%">
        Title
      </th>
      <th>
        Text Sample
      </th>
      <th>
        Date
      </th>
      <th>
        Actions
      </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.title %>
        </td>
        <td>
          <%= post.body.first(60) + "#{post.body.length > 60 ? "..." : ""}" %>
        </td>
        <td>
          <strong>Published on</strong> <%= post.created_at.strftime("%a, %d %B %Y %H:%M") %>
        </td>
        <td>
          <strong><%= link_to "View Full Post", post_url(post.id) %></strong> | <strong><%= link_to "Delete", destroy_post_url(post.id), method: :delete %></strong>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p class="float-right" style="margin-top: 30px">
<%= link_to "+ Add Post", new_post_url, class: "btn btn-primary" %>
</p>

app/views/posts/new.html.erb
<h1> Add a new post </h1>

<%= form_for @post, url: {action: "create"} do |f| %>
  <div class="form-group">
    <label for="title">Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="body">Body</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<hr>
<p style="margin-top: 2%">
  <%= @post.body %>
</p>

<%= link_to "Back", root_url, class: "mx-auto btn btn-primary" %>